/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev2;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.PrintStream;

public class AppTest {
    private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
    private final ByteArrayOutputStream errContent = new ByteArrayOutputStream();
    private final PrintStream originalOut = System.out;
    private final PrintStream originalErr = System.err;
    private final InputStream originalIn = System.in;

    @Before
    public void setUpStreams() {
        System.setOut(new PrintStream(outContent));
        System.setErr(new PrintStream(errContent));
    }
    @After
    public void restoreStreams() {
        System.setOut(new PrintStream(originalOut));
        System.setErr(new PrintStream(originalErr));
        System.setIn(originalIn);
    }

    @Test 
    public void taskShouldWorkProperty() {
        
        InputStream stream1 = new ByteArrayInputStream("6\n0 0 5 5 10 10\n".getBytes());
        System.setIn(stream1);
        App.main(null);

        assertEquals("30\n15\n", outContent.toString());
        outContent.reset();

        InputStream stream2 = new ByteArrayInputStream("7\n10 20 30 40 50 60 75\n".getBytes());
        System.setIn(stream2);
        App.main(null);

        assertEquals("285\n285\n", outContent.toString());
        outContent.reset();
    }
}
