import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {
    public static void main(String[] args) {
        int[][] A = new int[505][505];
        int[] H = new int[505];

        int n, m, L;
        Scanner scanner = new Scanner(System.in);

        n = scanner.nextInt();
        m = scanner.nextInt();
        L = scanner.nextInt();

        for (int i = 0; i < n; i++) {
            for (int j = 0; j < m; j++) {
                int temp = scanner.nextInt();
                A[i][j] = temp;
                H[temp]++;
            }
        }

        for (int i = 0; i < L; i++) {
            System.out.print(H[i]);
            if (i != L - 1) {
                System.out.print(' ');
            }
        }

        scanner.close();
    }
}
