import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 * @author famouscat
 */
public class App {

    static int unique(int[] temp) {
        int index = 1;
        for (int i = 1, len = temp.length; i < len; i++) {
            if (temp[i] != temp[i - 1]) {
                temp[index++] = temp[i];
            }
        }

        return index;
    }

    public static void main(String[] args) {

        Scanner scanner = new Scanner(System.in);
        int a = 10000;
        int[] b = new int[a + 10];
        int n = scanner.nextInt();
        int[] l = new int[n + 2];

        l[0] = 0;
        l[n + 1] = 0;
        for (int i = 1; i <= n; i++) {
            l[i] = scanner.nextInt();
        }

        int len = unique(l);

        for (int i = 1; i < len - 1; i++) {
            int t = l[i];
            int t0 = l[i - 1];
            int t2 = l[i + 1];

            if (t > t0 && t > t2) {
                b[t]++;
            }
            if (t < t0 && t < t2) {
                b[t]--;
            }
        }

        int temp = 0, sum = 0;
        for (int i = a; i > 0; i--) {
            sum += b[i];
            temp = temp > sum ? temp : sum;
        }

        scanner.close();
        System.out.println(temp);
    }
}
