import java.util.ArrayList;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 * @author famouscat
 */
public class App {

    static void unique(ArrayList<Integer> l) {
        for (int i = 0; i < l.size(); i++) {
            if (i + 1 < l.size() && l.get(i).equals(l.get(i + 1))) {
                l.remove(i + 1);
                i--;
            }
        }
    }

    public static void main(String[] args) {

        Scanner scanner = new Scanner(System.in);
        int M = 10000;
        int[] L = new int[M + 10];
        int n = scanner.nextInt();
        ArrayList<Integer> l = new ArrayList<Integer>(n + 100);

        l.add(0);
        for (int i = 1; i <= n; i++) {
            l.add(scanner.nextInt());
        }
        l.add(0);

        unique(l);

        for (int i = 1; i < l.size() - 1; i++) {
            Integer t = l.get(i);
            Integer t0 = l.get(i - 1);
            Integer t2 = l.get(i + 1);

            if (t > t0 && t > t2) {
                L[t]++;
            }
            if (t < t0 && t < t2) {
                L[t]--;
            }
        }

        int temp = 0, sum = 0;
        for (int i = M; i > 0; i--) {
            sum += L[i];
            temp = temp > sum ? temp : sum;
        }

        scanner.close();
        System.out.println(temp);
    }
}
