import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int n = scanner.nextInt();
        int N = scanner.nextInt();
        int sum = 0;

        int[] nums = new int[n + 2];
        nums[0] = 0;
        int[] subs = new int[n + 1];
        
        for(int i=1;i<n+1;i++) {
            nums[i] = scanner.nextInt();
        }
        nums[n + 1] = N;

        for(int j=0;j<n+1;j++) {
            subs[j] = nums[j+1] - nums[j];
            sum += subs[j] *j;
        }

        System.out.print(sum);
    }
}
